const products = [
  {
    id: 1,
    version: 'SuperSix EVO LAB71',
    name: 'SuperSix EVO LAB71 Dura-Ace Di2',
    model: 'Dura-ace di2',
    color: 'Marble Oxblood',
    description: 'Sculpted by Speed',
    about:
      'What happens when you design a complete bike, not just a frameset? An elegant design emerges alongside integrated aerodynamics. The frame, fork, bars, wheelsets, and seatpost are engineered as an entire system, achieving aerodynamic efficiency that blows away a piecemeal approach. It’s elevated design driven by elevated performance. Details you’ll notice. Speed you’ll feel.',
    price: (15000.0).toLocaleString(),
    sizes: ['44', '48', '51', '54', '56', '58', '61'],
    availablesizes: ['53'],
    image: '/cannondale/roadbikes/cannondale-supersix-evo-lab71-MOX1.webp',
    url: '/cannondale/road/supersixlab71',
    // Add other properties for the second product
    frame:
      'SuperSix EVO LAB71 Carbon, integrated cable routing w/ Switchplate, 12x142 Syntace thru-axle, BSA 68mm threaded BB, flat mount disc, integrated seat binder, SmartSense compatible',
    fork: 'SuperSix EVO LAB71 Carbon, integrated crown race, 12x100mm Syntace thru-axle, flat mount disc, internal routing, 1-1/8" to 1-1/4" Delta steerer, 55mm offset (44-54cm), 45mm offset (56-61cm)',
    rims: 'NEW Vision Metron60 SL Carbon, 60mm high, Tubeless-ready',
    hubs: '(F) Vision PRS, 12x100mm / (R) Vision PRS, 12x142mm',
    spokes: 'NEW Vision Metron2:1 aero bladed',
    tires: 'NEW Vittoria Corsa Pro, Tubeless, 700x28c',
    pedals: 'Not Included',
    crank: 'NEW FSA K-Force TEAM Edition Powerbox, 52/36T, w/ Powermeter',
    bottomBracket: 'NEW FSA Ceramic Bearing BSA',
    chain: 'Shimano Dura-Ace, 12-speed',
    rearCogs: 'Shimano Dura-Ace R9200, 11-30, 12-speed',
    frontDerailleur: 'Shimano Dura-Ace Di2 R9250',
    rearDerailleur: 'Shimano Dura-Ace Di2 R9250',
    shifters: 'Shimano Dura-Ace Di2 R9270, wireless, 2x12',
    handlebar: 'Cannondale System Bar R-One - low drag, full carbon integrated',
    grips: 'Prologo One Touch',
    brakes: 'Shimano Dura-Ace R9270, 160/140mm MT900 rotors',
    saddle: 'Prologo Dimension NACK NDR carbon',
    // (You can continue adding more properties if needed)
  },
  {
    id: 2,
    version: 'SuperSix EVO Hi-MOD',
    name: 'SuperSix EVO Hi-MOD Sram Red eTap AXS',
    model: 'SRAM Force AXS 12-speed',
    color: 'Marble Oxblood',
    description: 'Sculpted by Speed',
    about:
      'What happens when you design a complete bike, not just a frameset? An elegant design emerges alongside integrated aerodynamics. The frame, fork, bars, wheelsets, and seatpost are engineered as an entire system, achieving aerodynamic efficiency that blows away a piecemeal approach. It’s elevated design driven by elevated performance. Details you’ll notice. Speed you’ll feel.',
    price: (13500.0).toLocaleString(),
    sizes: ['44', '48', '51', '54', '56', '58', '61'],
    availablesizes: ['53'],
    image:
      '/cannondale/roadbikes/cannondale-supersix-evo-hi-mod-1-strictly-bicycles-1.webp',
    url: '/cannondale/road/supersixevohimod1',
    // Add other properties for the third product
    frame:
      'SuperSix EVO Hi-MOD Carbon, integrated cable routing w/ Switchplate, 12x142 Syntace thru-axle, BSA 68mm threaded BB, flat mount disc, integrated seat binder, SmartSense compatible',
    fork: 'SuperSix EVO Hi-MOD Carbon, integrated crown race, 12x100mm Syntace thru-axle, flat mount disc, internal routing, 1-1/8" to 1-1/4" Delta steerer, 55mm offset (44-54cm), 45mm offset (56-61cm)',
    rearShock: 'Null',
    rims: 'HollowGram 50 R-SL, Carbon, 20h front, 24h rear, 50mm deep, 21mm IW, tubeless ready',
    hubs: '(F) HollowGram, sealed bearing 12x100mm centerlock / (R) HollowGram, 12x142mm centerlock w/ DT Swiss 240 internals',
    spokes: 'DT Swiss Aerolite, straight-pull',
    tires: 'Continental Grand Prix 5000, 700 x 25c',
    pedals: 'Not included',
    crank: 'SRAM RED AXS Carbon, 48/35',
    bottomBracket: 'SRAM DUB BSA',
    chain: 'SRAM RED, 12-speed',
    rearCogs: 'SRAM XG-1290, 10-28, 12-speed',
    frontDerailleur: 'SRAM RED AXS',
    rearDerailleur: 'SRAM RED AXS',
    shifters: 'SRAM RED eTap AXS HRD, 2x12',
    handlebar:
      'Cannondale SystemBar R-One - low drag, full carbon integrated bar/stem, internal routing',
    grips: 'Fizik Tempo Bondcush Soft, 3mm',
    stem: 'Cannondale SystemBar R-One - low drag, full carbon integrated bar/stem, internal routing',
    headset: 'Integrated, 1-1/8" - 1-1/4"',
    eBikeCharger: 'Null',
    brakes: 'SRAM RED eTap AXS HRD, 160/160mm Centerline-X rotors',
    saddle: 'Prologo Dimension NACK NDR, Carbon Rails',
    seatpost:
      'Cannondale C1 Aero 40 Carbon, 0mm offset (44-48cm), 20mm offset (51-61cm)',
    extras:
      'Cannondale Gripper Aero Bottles & ReGrip Aero Cages, SRAM AXS charger',
    // (You can continue adding more properties if needed)
  },
  {
    id: 3,
    version: 'SystemSix Hi-MOD ',
    name: 'SystemSix Hi-MOD Dura-Ace Di2',
    model: 'Dura-ace di2',
    color: 'Mercury',
    description: 'Faster Everywhere',
    about:
      'SystemSix outstrips opponents, and not just where you’d expect. It sprints, descends and even climbs most hills faster, conserving watts off the front, in the draft, and in the laughing group.',
    price: (13050.0).toLocaleString(),
    sizes: ['47', '51', '54', '56', '58'],
    availablesizes: ['53'],
    image:
      '/cannondale/roadbikes/cannondale-systemsix-hi-mod-dura-ace-di2-strictly-bicycles-1_93f72e40-d44c-4c17-a650-f33c1ea071c0 (1).webpSystemSix-Hi-MOD-Dura-Ace-Di2.png',
    url: '/cannondale/road/systemsix/',
    // Add other properties for the second product
    frame:
      'Hi-MOD Carbon, integrated cable routing w/ Switchplate, SAVE, PF30a, flat mount disc, 12x142 Speed Release thru-axle',
    fork: 'Hi-MOD Carbon, 1-1/8" - 1-1/4" steerer, 12x100mm Speed Release thru-axle, flat mount disc, 55mm offset (47-51cm) 45mm offset (54-62cm)',
    rims: 'HollowGram 64 SL KNØT, Carbon, 20h front, 24h rear, 64mm deep, 21mm IW, tubeless ready',
    hubs: '(F) HollowGram KNØT, sealed bearing 12x100mm centerlock / (R) HollowGram KNØT, 12x142mm centerlock w/ DT Swiss 240 internals',
    spokes: 'DT Swiss Aerolite, straight-pull',
    tires: 'Vittoria Rubino Pro Speed, 700 x 25c',
    pedals: 'Not included',
    crank: 'Shimano Dura-Ace R9200, 52/36 for 12-speed',
    bottomBracket: 'Cannondale Alloy PressFit30',
    chain: 'Shimano CN-M9100, 12-speed',
    rearCogs: 'Shimano Dura-Ace R9200, 11-30, 12-speed',
    frontDerailleur: 'Shimano Dura-Ace Di2 R9250, braze-on',
    rearDerailleur: 'Shimano Dura-Ace Di2 R9250',
    shifters: 'Shimano Dura-Ace Di2 R9270, 12-speed',
    handlebar: 'HollowGram KNØT SystemBar, Carbon, 8 deg. pitch adjust',
    grips: 'Cannondale Bar Tape, 3.5mm',
    stem: 'HollowGram KNØT, Alloy w/ cable cover, -17°',
    headset: 'Integrated, 1-1/8" - 1-1/4',
    brakes: 'Shimano Dura Ace Di2 R9270 hydraulic disc, 160/140mm MT900 rotors',
    saddle: 'Fizik Tempo Argo R3, 150mm width, K:ium rails',
    seatpost: 'HollowGram 60 KNØT Carbon, 330mm',
  },
  {
    id: 4,
    version: 'SuperSix EVO Hi-MOD 2',
    name: 'SystemSix Hi-MOD Ultegra Di2',
    model: 'Ultegra di2',
    color: 'Matte Black',
    description: 'Faster Everywhere',
    about:
      'SystemSix outstrips opponents, and not just where you’d expect. It sprints, descends and even climbs most hills faster, conserving watts off the front, in the draft, and in the laughing group.',
    price: (8300.0).toLocaleString(),
    sizes: ['44', '48', '51', '54', '56', '58', '61'],
    availablesizes: ['53'],
    image: '/cannondale/roadbikes/cannondale-supersix-evo-hi-mod-2-MOX.webp',
    url: '/cannondale/road/supersixevohimod2',
    // Add other properties for the fourth product
    frame:
      'SuperSix EVO Hi-MOD Carbon, integrated cable routing w/ Switchplate, 12x142 Syntace thru-axle, BSA 68mm threaded BB, flat mount disc, integrated seat binder, SmartSense compatible',
    fork: 'SuperSix EVO Hi-MOD Carbon, integrated crown race, 12x100mm Syntace thru-axle, flat mount disc, internal routing, 1-1/8" to 1-1/4" Delta steerer, 55mm offset (44-54cm), 45mm offset (56-61cm)',
    rims: 'HollowGram R-SL 50, Carbon, 20h front, 24h rear, 50mm deep, 21mm inner width, tubeless ready',
    hubs: '(F) HollowGram, sealed bearing 12x100mm centerlock / (R) HollowGram, 12x142mm centerlock w/ DT Swiss 240 internals',
    spokes: 'DT Swiss Aerolite, straight-pull',
    tires: 'Continental Grand Prix 5000, 700x25c',
    pedals: 'Not included',
    crank: 'Shimano Ultegra R8100, 52/36',
    bottomBracket: 'Shimano BSA 68',
    chain: 'Shimano Ultegra, 12-speed',
    rearCogs: 'Shimano Ultegra R8100, 11-30, 12-speed',
    frontDerailleur: 'Shimano Ultegra Di2 R8150',
    rearDerailleur: 'Shimano Ultegra Di2 R8150',
    shifters: 'Shimano Ultegra Di2 R8170, wireless, 2x12',
    handlebar: 'Vision Trimax Carbon Aero, 31.8mm',
    grips: 'Fizik Tempo Bondcush Soft, 3mm',
    stem: 'Cannondale C1 Conceal, Alloy, 31.8, -6°',
    headset: 'Integrated, 1-1/8" - 1-1/4"',
    brakes: 'Shimano Ultegra R8170, 160/140mm MT800 rotors',
    saddle: 'Prologo Dimension TiRox NDR, Titanium Rails',
    seatpost:
      'Cannondale C1 Aero 40 Carbon, 0mm offset (44-48cm), 20mm offset (51-61cm)',

    extras:
      'Cannondale Gripper Aero Bottles & ReGrip Aero Cages, Shimano EC300 charging connector',
    // (You can continue adding more properties if needed)
  },
  {
    id: 5,
    version: 'SuperSix EVO 1',
    name: 'SystemSix Hi-MOD SRAM Force eTap AXS',
    model: 'SRAM Force AXS 12-speed',
    color: 'Mystique Gray',
    description: 'Faster Everywhere',
    about:
      'SystemSix outstrips opponents, and not just where you’d expect. It sprints, descends and even climbs most hills faster, conserving watts off the front, in the draft, and in the laughing group.',
    price: (7000.0).toLocaleString(),
    sizes: ['44', '48', '51', '54', '56', '58', '61'],
    availablesizes: ['53'],
    image: '/cannondale/roadbikes/cannondale-supersix-evo-1-MOX.webp',
    url: '/cannondale/road/supersixevo1',
    // Add other properties for the fifth product
    frame:
      'SuperSix EVO Carbon, integrated cable routing w/ Switchplate, 12x142 Syntace thru-axle, BSA 68mm threaded BB, flat mount disc, integrated seat binder, SmartSense compatible',
    fork: 'SuperSix EVO Carbon, integrated crown race, 12x100mm Syntace thru-axle, flat mount disc, internal routing, 1-1/8" to 1-1/4" Delta steerer, 55mm offset (44-54cm), 45mm offset (56-61cm)',
    rims: 'HollowGram 50 R-S, Carbon, 20h front, 24h rear, 50mm deep, 21mm IW, tubeless ready',
    hubs: '(F) HollowGram, sealed bearing 12x100mm centerlock / (R) HollowGram, 12x142mm centerlock w/ DT Swiss 350 internals',
    spokes: 'Formula Grand Forza, Double Butted, straight-pull',
    tires: 'Vittoria Rubino Pro Bright Black, 700 x 25c, reflective strip',
    pedals: 'Not included',
    crank: 'SRAM Force, DUB, 48/35',
    bottomBracket: 'SRAM DUB BSA',
    chain: 'SRAM Force, 12-speed',
    rearCogs: 'SRAM XG-1270, 10-33, 12-speed',
    frontDerailleur: 'SRAM Force AXS, braze-on',
    rearDerailleur: 'SRAM Force AXS',
    shifters: 'SRAM Force AXS, 12-speed',
    handlebar: 'Vision Trimax Carbon Aero, 31.8mm',
    grips: 'Cannondale Bar Tape, 3.5mm',
    stem: 'Cannondale C1 Conceal, Alloy, 31.8, -6°',
    headset: 'Integrated, 1-1/8" - 1-1/4"',
    brakes: 'SRAM Force AXS Hydraulic Disc, 160/160mm PaceLine Rotors',
    saddle: 'Prologo Dimension TiRox NDR, Titanium Rails',
    seatpost:
      'Cannondale C1 Aero 40 Carbon, 0mm offset (44-48cm), 20mm offset (51-61cm)',
    extras: 'SRAM AXS charger',
    // (You can continue adding more properties if needed)
  },
  {
    id: 6,
    version: 'SuperSix EVO 2',
    name: 'SuperSix EVO 2 Ultegra Di2',
    model: 'Ultegra di2',
    color: 'Raw Carbon',
    description: 'Faster Everywhere',
    about:
      'SystemSix outstrips opponents, and not just where you’d expect. It sprints, descends and even climbs most hills faster, conserving watts off the front, in the draft, and in the laughing group.',
    price: (5500.0).toLocaleString(),
    sizes: ['44', '48', '51', '54', '56', '58', '61'],
    availablesizes: ['53'],
    image: '/cannondale/roadbikes/C23_C11453U_SuperSix_EVO_Crb_2_RAW_MOX.webp',
    url: '/cannondale/road/supersixevo2',
    // Add other properties for the sixth product
    frame:
      'SuperSix EVO Carbon, integrated cable routing w/ Switchplate, 12x142 Syntace thru-axle, BSA 68mm threaded BB, flat mount disc, integrated seat binder, SmartSense compatible',
    fork: 'SuperSix EVO Carbon, integrated crown race, 12x100mm Syntace thru-axle, flat mount disc, internal routing, 1-1/8" to 1-1/4" Delta steerer, 55mm offset (44-54cm), 45mm offset (56-61cm)',
    rims: 'HollowGram 45 R, Carbon, 20h front, 24h rear, 50mm deep, 21mm IW, tubeless ready',
    hubs: '(F) HollowGram, sealed bearing 12x100mm centerlock / (R) HollowGram 3-pawl, sealed bearing, 12x142mm centerlock',
    spokes: 'Formula Grand Forza, Double Butted, straight-pull',
    tires: 'Vittoria Rubino Pro Bright Black, 700 x 25c, reflective strip',
    pedals: 'Not included',
    crank: 'Shimano Ultegra R8100, 52/36',
    bottomBracket: 'Shimano BBRS500, BSA',
    chain: 'Shimano Ultegra, 12-speed',
    rearCogs: 'Shimano Ultegra R8100, 11-30, 12-speed',
    frontDerailleur: 'Shimano Ultegra Di2 R8150',
    rearDerailleur: 'Shimano Ultegra Di2 R8150',
    shifters: 'Shimano Ultegra Di2 R8170, wireless, 2x12-speed',
    handlebar: 'Vision Trimax Carbon Aero, 31.8mm',
    grips: 'Cannondale Bar Tape, 3.5mm',
    stem: 'Cannondale C1 Conceal, Alloy, 31.8, -6°',
    headset: 'Integrated, 1-1/8" - 1-1/4"',
    brakes: 'Shimano Ultegra R8170, 160/140mm MT800 rotors',
    saddle: 'Prologo Dimension STN NDR, Stainless Steel Rails',
    seatpost:
      'Cannondale C1 Aero 40 Carbon, 0mm offset (44-48cm), 20mm offset (51-61cm)',

    extras: 'Shimano EC300 charging connector',
    // (You can continue adding more properties if needed)
  },
  {
    id: 7,
    version: 'SuperSix EVO',
    name: 'SuperSix EVO Rival eTap AXS',
    model: 'SRAM Rival AXS 12-speed',
    color: 'Mantis',
    description: 'Faster Everywhere',
    about:
      'SystemSix outstrips opponents, and not just where you’d expect. It sprints, descends and even climbs most hills faster, conserving watts off the front, in the draft, and in the laughing group.',
    price: (4650.0).toLocaleString(),
    sizes: ['44', '48', '51', '54', '56', '58', '60', '62'],
    availablesizes: ['53'],
    image: '/cannondale/roadbikes/cannondale-supersix-evo-se-MOX.webp',
    url: '/cannondale/road/supersixevo3',
    // Add other properties for the eighth product
    frame:
      'BallisTec Carbon, integrated cable routing w/ Switchplate, 12x142 Speed Release thru-axle, SAVE, PF30a, flat mount disc, integrated seat binder',
    fork: 'BallisTec Carbon, SAVE, integrated crown race, 12x100mm Speed Release thru-axle, flat mount disc, internal routing, 1-1/8" to 1-1/4" steerer and 55mm offset (44-54cm), 1-1/8" to 1-3/8 steerer and 45mm offset (56-62cm)',
    rims: 'DT Swiss R470 db, 28h',
    hubs: '(F) Formula CL-712, 12x100mm centerlock / (R) Formula RXC-400, 12x142mm centerlock',
    spokes: 'Stainless Steel, 14g',
    tires: 'Vittoria Rubino Pro Bright Black, 700 x 25c',
    pedals: 'Not included',
    crank: 'SRAM Rival DUB X-Range, 46/33',
    bottomBracket: 'SRAM DUB PF30A Road 73mm',
    chain: 'SRAM Rival 12-speed',
    rearCogs: 'SRAM Rival XG-1250, 12-speed 10-36',
    frontDerailleur: 'SRAM Rival eTap AXS, braze-on',
    rearDerailleur: 'SRAM Rival eTap AXS',
    shifters: 'SRAM Rival eTap AXS HRD',
    handlebar: 'HollowGram SAVE SystemBar, Carbon, 8 deg. pitch adjust',
    grips: 'Cannondale Bar Tape, 3.5mm',
    stem: 'HollowGram KNØT, Alloy w/ cable cover, -6°',
    headset: 'Integrated, 1-1/8" - 1-1/4" (44-54cm), 1-1/8" - 1-3/8" (56-62cm)',
    brakes: 'SRAM Rival hydraulic disc, 160/160mm Paceline rotors',
    saddle: 'Fizik Aliante Delta, S-alloy rails',
    seatpost:
      'HollowGram 27 SL KNØT, Carbon, 2 bolt clamp, 330mm, 0mm offset (44-48cm), 15mm offset (51-62cm)',

    extras: 'Removable fender bridge',
    // (You can continue adding more properties if needed)
  },
  {
    id: 8,
    version: 'SuperSix EVO 3',
    name: 'SuperSix EVO 3 105 Di2',
    model: '105 di2',
    color: 'Chalk',
    description: 'Faster Everywhere',
    about:
      'SystemSix outstrips opponents, and not just where you’d expect. It sprints, descends and even climbs most hills faster, conserving watts off the front, in the draft, and in the laughing group.',
    price: (4500.0).toLocaleString(),
    sizes: ['44', '48', '51', '54', '56', '58', '61'],
    availablesizes: ['53'],
    image: '/cannondale/roadbikes/cannondale-supersix-evo-3-MOX.webp',

    url: '/cannondale/road/supersixevo4',
    // Add other properties for the seventh product
    frame:
      'SuperSix EVO Carbon, integrated cable routing w/ Switchplate, 12x142 Syntace thru-axle, BSA 68mm threaded BB, flat mount disc, integrated seat binder, SmartSense compatible',
    fork: 'SuperSix EVO Carbon, integrated crown race, 12x100mm Syntace thru-axle, flat mount disc, internal routing, 1-1/8" to 1-1/4" Delta steerer, 55mm offset (44-54cm), 45mm offset (56-61cm)',
    rims: 'DT Swiss R470 db, 28h',
    hubs: '(F) Formula CL-712, 12x100mm centerlock / (R) Formula RXC-400, 12x142mm centerlock',
    spokes: 'Stainless Steel, 14g',
    tires: 'Vittoria Rubino Pro Bright Black, 700 x 25c, reflective strip',
    pedals: 'Not included',
    crank: 'Shimano 105 R7100, 50/34',
    bottomBracket: 'Shimano BB-RS500, BSA',
    chain: 'Shimano 105, 12-speed',
    rearCogs: 'Shimano 105 R7100, 11-34, 12-speed',
    frontDerailleur: 'Shimano 105 Di2 R7170',
    rearDerailleur: 'Shimano 105 Di2 R7150',
    shifters: 'Shimano 105 Di2 R7170, wireless, 2x12-speed',
    handlebar: 'Vision Trimax Aero, 31.8mm',
    grips: 'Cannondale Bar Tape, 3.5mm',
    stem: 'Cannondale C1 Conceal, Alloy, 31.8, -6°',
    headset: 'Integrated, 1-1/8" - 1-1/4"',
    brakes: 'Shimano 105 R7170 hydraulic disc, 160/160mm RT70 rotors',
    saddle: 'Prologo Nago RS STN, Stainless Steel Rails',
    seatpost:
      'Cannondale C1 Aero 40 Carbon, 0mm offset (44-48cm), 20mm offset (51-61cm)',

    extras: 'Shimano EC300 charging connector',
    // (You can continue adding more properties if needed)
  },
];

export default products;
