version: '3.7'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mox-multisport
    ports:
      - '3000:3000'
    volumes:
      - .:/app
      - /app/node_modules